apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-extra
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: guestbook-ui
